travis:
  secure:
    BINSTAR_TOKEN: QXZ/IQdSA5OM904mI2rdvhu2od91czWqrPHyBDenJhKE72GKM0jgr/65SgYGmbkmCIswFtNKcWP/RP3i/BganU3cD9yq/y68HvejfRXy7TcoLBn+JPJ4w7OH51pMZxWsV+3ie09bLo1eNU+skCdgLko7rGS9JuTFwLbA8+TfTk/pH9ktFMh6K1BADkLnxcr2mEg/h+6TBx20Fc+5jxG1wLtRJG+XdASP2tAQxu91DdXBoMTq9mKcrqt5SzyaQ6sy6M+J9LL9hUU1IWOirMlpRVtx+FYSD97jOWGkQ40J6crMy4aBi2H+2dN+FuXjP72JwjEmuIgbnU/W4CMrqPqKBgiTjOOJFpk1VlJHLMdrcvKn34RifiRvfy1skj6wKi8IFftwarnj8PLHQs++dVtW5IOPymItelSlSbl1kNAr6fGyIQoUGNLvlec/6L8ETx+XI1yzG6n7VskcnzIQqVYaxkHGTnVbOnTXxKqTpKowRyfeaCYr1KGKO1hhq00b3RMVRo4P6b4AhwlE5I7ntv01Dv42AzPN5DsoXQlnGYIDfgj2Na2SUYjTjiDYfvDwslQDit4sfDSUMSRzGr3q0Gq2XNaDO1uO6wOd3uGpYd3m5jmdI786D8fveR1kAVel8lCvWtLor/wY7Bsi08exHdN2nxE+e3YLJrpgGp2Kc4hr/Ro=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
